services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file: .env.dev
    volumes:
      - ./server:/app
      - /app/.venv
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file: .env.dev
    volumes:
      - ./web:/app
      - /app/node_modules

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env.dev
    ports:
      - "6379:6379"

volumes:
  pgdata:
