services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file: .env.dev
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file: .env.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env.dev
    ports:
      - "6379:6379"

volumes:
  pgdata:
