# DEV-ONLY DOCKERFILE
ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim

WORKDIR /app

RUN pip install uv

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY pyproject.toml uv.lock /app/

RUN uv sync --locked

COPY . /app/

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
CMD uv run uvicorn --host 0.0.0.0 --port 8000 --reload app.main:app
