[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.2.0",
    "fastapi>=0.115.13",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.9.1",
    "uvicorn[standard]>=0.34.3",
]
