# DEV-ONLY DOCKERFILE
ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim

WORKDIR /app

ENV BETTER_EXCEPTIONS=1
ENV PYTHONUNBUFFERED=1

RUN pip install uv better-exceptions

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY pyproject.toml uv.lock ./

RUN uv sync --locked

COPY . /app/

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--reload", "app.main:app"]
