"""added indexes

Revision ID: 981fe1c79dfe
Revises: 9248351a3ea7
Create Date: 2025-08-06 07:48:00.047973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981fe1c79dfe'
down_revision: Union[str, Sequence[str], None] = '9248351a3ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_identities_provider'), 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider_email'), 'auth_identities', ['provider_email'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider_user_id'), 'auth_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_backup_codes_user_id'), 'backup_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_mfa_credentials_confirmed'), 'mfa_credentials', ['confirmed'], unique=False)
    op.create_index(op.f('ix_mfa_credentials_method'), 'mfa_credentials', ['method'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_mfa_credentials_method'), table_name='mfa_credentials')
    op.drop_index(op.f('ix_mfa_credentials_confirmed'), table_name='mfa_credentials')
    op.drop_index(op.f('ix_backup_codes_user_id'), table_name='backup_codes')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider_email'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider'), table_name='auth_identities')
    # ### end Alembic commands ###
