# DEV-ONLY DOCKERFILE
ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-slim

WORKDIR /app

COPY package*.json ./
RUN npm clean-install

COPY . /app

EXPOSE 5173

CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "5173", "--strictPort"]
