/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/(settings)/settings': RouteRecordInfo<'/(settings)/settings', '/settings', Record<never, never>, Record<never, never>, '/(settings)/settings/' | '/(settings)/settings/account' | '/(settings)/settings/authentication-identities' | '/(settings)/settings/devices' | '/(settings)/settings/mfa'>,
    '/(settings)/settings/': RouteRecordInfo<'/(settings)/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/(settings)/settings/account': RouteRecordInfo<'/(settings)/settings/account', '/settings/account', Record<never, never>, Record<never, never>>,
    '/(settings)/settings/authentication-identities': RouteRecordInfo<'/(settings)/settings/authentication-identities', '/settings/authentication-identities', Record<never, never>, Record<never, never>>,
    '/(settings)/settings/devices': RouteRecordInfo<'/(settings)/settings/devices', '/settings/devices', Record<never, never>, Record<never, never>>,
    '/(settings)/settings/mfa': RouteRecordInfo<'/(settings)/settings/mfa', '/settings/mfa', Record<never, never>, Record<never, never>>,
    '/(admin)/admin': RouteRecordInfo<'/(admin)/admin', '/admin', Record<never, never>, Record<never, never>, '/(admin)/admin/' | '/(admin)/admin/dashboard' | '/(admin)/admin/logs' | '/(admin)/admin/users'>,
    '/(admin)/admin/': RouteRecordInfo<'/(admin)/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/dashboard': RouteRecordInfo<'/(admin)/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/logs': RouteRecordInfo<'/(admin)/admin/logs', '/admin/logs', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/users': RouteRecordInfo<'/(admin)/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth/local/forgot-password': RouteRecordInfo<'/auth/local/forgot-password', '/auth/local/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login/magic-link/': RouteRecordInfo<'/auth/login/magic-link/', '/auth/login/magic-link', Record<never, never>, Record<never, never>>,
    '/auth/login/magic-link/register': RouteRecordInfo<'/auth/login/magic-link/register', '/auth/login/magic-link/register', Record<never, never>, Record<never, never>>,
    '/auth/login/password/': RouteRecordInfo<'/auth/login/password/', '/auth/login/password', Record<never, never>, Record<never, never>>,
    '/auth/login/password/register': RouteRecordInfo<'/auth/login/password/register', '/auth/login/password/register', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/auth/mfa/backup-code': RouteRecordInfo<'/auth/mfa/backup-code', '/auth/mfa/backup-code', Record<never, never>, Record<never, never>>,
    '/auth/mfa/totp': RouteRecordInfo<'/auth/mfa/totp', '/auth/mfa/totp', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
  }
}
